isnlila/ligne/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from isnlila.ligne import views

urlpatterns = patterns('',
        url(r'^all/$', views.all, name='ligne.all'),
        url(r'^(?P<short_name>.+)/$', views.ligne, name='ligne.ligne'),
)

isnlila/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = patterns('',
    # Examples:
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', RedirectView.as_view(pattern_name='search.stop', permanent=False)),
    url(r'^horaires/', include('isnlila.horaires.urls')),
    url(r'^ligne/', include('isnlila.ligne.urls')),
    url(r'^search/', include('isnlila.search.urls')),
    url(r'^carte/', include('isnlila.carte.urls')),
)

isnlila/ligne/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django import forms

from isnlila.lila.models import StopRoute

class StopLigneForm(forms.Form) :
    sens = forms.ChoiceField(required=False)
    def __init__(self, *args, **kwargs):
        short_name = kwargs.pop('short_name')
        super(StopLigneForm, self).__init__(*args, **kwargs)
        self.fields['sens'].choices = StopRoute.objects.filter(route__short_name=short_name).values_list('route__route_id', 'terminus').distinct()

isnlila/ligne/views.py
from django.shortcuts import render
from django.http import JsonResponse

from isnlila.lila.models import Route, StopRoute
from isnlila.ligne.forms import StopLigneForm

def all(request):
    routes = Route.objects.all()
    short_names = set()
    routes = [r for r in routes if not (r.short_name in short_names or short_names.add(r.short_name))]
    return render(request, 'lignes/index.html', {
        'routes': routes
        }
    )

def ligne(request, short_name):
    stop_routes = []
    if request.method == 'GET':
        form = StopLigneForm(short_name=short_name)
    else:
        form = StopLigneForm(request.POST, short_name=short_name)
        if form.is_valid():
            route_id = form.cleaned_data['sens']
            stop_routes = StopRoute.objects.filter(route__route_id=route_id).order_by('stop__name')

    return render(request, 'lignes/ligne.html', {
        'form': form,
        'short_name': short_name,
        'stop_routes': stop_routes,
        }
    )

templates/lignes/index.html
{% extends "base.html" %}

{% load staticfiles %}

{% block content %}
<h4>Lignes : </h4>
<ul class="collection">
    {% for r in routes %}
    <li class="collection-item avatar">
        <div class="circle" style="background-color: {{ r.color }}">{{ r.short_name }}</div>
        <span class="title"><a href="/ligne/{{ r.short_name }}">{{ r.long_name }}</a></span>
    </li>
    {% endfor %}
</ul>
{% endblock %}

templates/lignes/ligne.html
{% extends "base.html" %}

{% load staticfiles %}

{% block scripts %}
$('#id_sens').material_select();
{% endblock %}



{% block content %}
<div class="row">
        <form action="/ligne/{{ short_name }}/" method="post" class="col s12 form" id="search-form">
        {% csrf_token %}
        <div class="row">
            <div class="input-field col s6 offset-s3">
                {{ form.sens }}
            </div>
        </div>
        <div class="row center">
            <button class="btn waves-effect waves-light" type="submit" name="action">Valider
                <i class="mdi-content-send right"></i>
            </button>
        </div>
    </form>
</div>

<div class="row">
    {% if stop_routes %}
    <div class="collection">
        {% for s in stop_routes %}
        <a class="collection-item" href="/horaires/view/{{ s.id }}/"><i class="small mdi-maps-directions-bus left"></i>{{ s.stop.name }} ({{ s.stop.city }})</a>
        {% endfor %}
    </div>
    {% endif %}
</div>
{% endblock %}