isnlila/horaires/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from isnlila.horaires import views

urlpatterns = patterns('',
        url(r'^view/(?P<sr_id>\d+)/$', views.view, name='horaires.view'),
        url(r'^trip/(?P<trip_id>.+)/$', views.trip, name='horaires.trip'),
)

isnlila/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = patterns('',
    # Examples:
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', RedirectView.as_view(pattern_name='search.stop', permanent=False)),
    url(r'^horaires/', include('isnlila.horaires.urls')),
    url(r'^ligne/', include('isnlila.ligne.urls')),
    url(r'^search/', include('isnlila.search.urls')),
    url(r'^carte/', include('isnlila.carte.urls')),
)

isnlila/horaires/forms.py
from django import forms
from datetime import date

class DateForm(forms.Form) :
    date = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'datepicker', 'autocomplete': 'off', 'value': date.today().strftime('%d/%m/%Y')}))

isnlila/horaires/views.py
from django.shortcuts import render
from django.http import JsonResponse

from isnlila.horaires.forms import DateForm
from isnlila.lila.models import StopRoute, StopTime, CalendarDate, Calendar, Trip
from datetime import datetime, date, time

def view(request, sr_id):
    stop_route = StopRoute.objects.select_related().get(id=sr_id)
    route_id = stop_route.route.route_id
    stop_id = stop_route.stop.stop_id
    direction_id = stop_route.direction_id
    stop_times = []
    date = None

    if request.method == 'GET':
        form = DateForm()
    else:
        form = DateForm(request.POST)
        if form.is_valid():
            date = datetime.strptime(form.cleaned_data['date'], '%d/%m/%Y')
            days = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday']

            f = {'start_date__lte':date, 'end_date__gte':date, days[date.weekday()]: 1}
            services = set(Calendar.objects.filter(**f).values_list('service_id', flat=True))

            for c in CalendarDate.objects.filter(date=date, exception_type=1):
                services.add(c.service_id)
            for c in CalendarDate.objects.filter(date=date, exception_type=2):
                services.discard(c.service_id)

            st = StopTime.objects.filter(
                    trip__service_id__in=services,
                    trip__route__route_id=route_id,
                    trip__direction_id=direction_id,
                    stop_id=stop_id
                ).order_by('arrival_time')


            arrivals = set()
            stop_times = [s for s in st if not (s.arrival_time in arrivals or arrivals.add(s.arrival_time))]

    return render(request, 'horaires/view.html', {
        'sr_id': sr_id,
        'stop_route': stop_route,
        'stop_times': stop_times,
        'form' : form,
        'date': date
        }
    )


def trip(request, trip_id):
    st = StopTime.objects.filter(trip__trip_id=trip_id)

    arrivals = set()
    stop_times = [s for s in st if not (s.arrival_time in arrivals or arrivals.add(s.arrival_time))]

    return render(request, 'horaires/trip.html', {
        'stop_times': stop_times
        }
    )

templates/horaires/trip.html
{% extends "base.html" %}

{% block content %}


<h4 class="center">Voyage du car</h4>

<table class="striped">
    <thead>
        <tr>
            <th data-field="stop">Arrêt</th>
            <th>Ville</th>
            <th data-field="hour">Heure</th>
        </tr>
    </thead>

    <tbody>
        {% for s in stop_times %}
        <tr>
            <td>{{ s.stop.name }}</td>
            <td>{{ s.stop.city }}</td>
            <td>{{ s.arrival_time|time:'H:i'}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/horaires/view.html
{% extends "base.html" %}

{% load staticfiles %}

{% block nav_color %}{{ stop_route.route.color }}{% endblock %}
{% block footer_color %}{{ stop_route.route.color }}{% endblock %}

{% block scripts %}
$('.datepicker').pickadate({
    format: 'dd/mm/yyyy',
    onSet: function(context) {
        this.close();
    }
});
{% endblock %}

{% block content %}

<div class="row">
    <form action="{% url 'horaires.view' sr_id %}" method="POST" class="col s12 form">
        {% csrf_token %}
        <div class="row">
            <div class="input-field col s12">
                {{ form.date }}
                <label for="id_date">Date</label>
            </div>
        </div>
        <div class="row center">
            <button class="btn waves-effect waves-light" type="submit" name="action">Valider
                <i class="mdi-content-send right"></i>
            </button>
        </div>
    </form>
</div>
<div class="row">
    <ul class="collection with-header">
        <li class="collection-header">
            <h4 class="flow-text"><div class="center"><b>Horaires à l'arret {{ stop_route.stop.name }} ({{ stop_route.stop.city }})  </b></div>
                <div class="center">
                    Ligne
                    <span class="circle" style="display: inline-block;background-color: {{ stop_route.route.color }}">{{ stop_route.route.short_name }}</span> 
                    : {{ stop_route.route.long_name }}
                    <i class="tiny mdi-navigation-arrow-forward sens"></i>
                    {{ stop_route.terminus }}
                    le {{ date|date:"d/m/Y" }}
                </div>
            </h4>
        </li>
        {% for s in stop_times %}
        <a href="{% url 'horaires.trip' s.trip.trip_id %}" class="collection-item">{{ s.arrival_time|time:'H:i'}}</a>
        {% endfor %}
    </ul>
</div>
{% endblock %}