isnlila/search/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from isnlila.search import views

urlpatterns = patterns('',
        url(r'^stop/$', views.search_stop, name='search.stop'),
        url(r'^suggest/stop/(?P<search>[\w\W]+)/$', views.suggest_stop, name='search.suggest_stop'),
)

isnlila/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = patterns('',
    # Examples:
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', RedirectView.as_view(pattern_name='search.stop', permanent=False)),
    url(r'^horaires/', include('isnlila.horaires.urls')),
    url(r'^ligne/', include('isnlila.ligne.urls')),
    url(r'^search/', include('isnlila.search.urls')),
    url(r'^carte/', include('isnlila.carte.urls')),
)

isnlila/search/forms.py
from django import forms

class SearchStopForm(forms.Form) :
    stop = forms.CharField(required=False, widget=forms.TextInput(attrs={'autocomplete': 'off'}))
    long_name = forms.CharField(required=True, widget=forms.HiddenInput())

isnlila/search/views.py
from django.shortcuts import render
from django.http import JsonResponse

from isnlila.search.forms import SearchStopForm
from isnlila.lila.models import StopRoute

def search_stop(request):
    stop_routes = []
    if request.method == 'GET':
        form = SearchStopForm()
    else:
        form = SearchStopForm(request.POST)
        if form.is_valid():
            long_name = form.cleaned_data['long_name']
            stop_routes = StopRoute.objects.filter(long_name=long_name).select_related()

    return render(request, 'search/stop.html', {
        'form': form,
        'stop_routes': stop_routes,
        }
    )

# JSON

def suggest_stop(request, search):
    stop_routes = [{
        'long_name': "%s|%s" % (s['stop__name'], s['stop__city'])
        } for s in StopRoute.objects
                        .filter(long_name__contains=search)
                        .values('stop__name', 'stop__city')
                        .distinct()
                        .order_by('stop__name', 'stop__city')
    ]
    return JsonResponse({"results": stop_routes})

templates/search/stop.html
{% extends "base.html" %}

{% load staticfiles %}

{% block scripts %}
$('.suggestions').hide();
var search_input = $('#id_stop');
search_input.on('input', function() {
    var stop_val = search_input.val();
    if(stop_val.length > 1) {
        $('.suggestions').empty();
        $('.suggestions').show();
        url = '/isnlila/search/suggest/stop/'+stop_val+'/';
        $.getJSON(url, function(data){
            var results = data.results;
            $.each(results, function(e) {
                var long_name_spl = results[e].long_name.split('|');
                var long_name = long_name_spl[0];
                long_name += long_name_spl[1] != '' ? ' ('+long_name_spl[1]+')' : '';
                $('<a>')
                    .addClass('collection-item')
                    .attr('href', '#!')
                    .append('<i class="small mdi-maps-directions-bus left"></i>')
                    .append(long_name)
                    .appendTo('.suggestions')
                    .click(function(ev) {
                        $('#id_long_name').val(long_name_spl[0]+' '+long_name_spl[1]);
                        $('#search-form').submit();
                    });
            });
        })
    } else {
        $('.suggestions').hide();
    }
});
{% endblock %}



{% block content %}
<div class="row">
    <h1 class="center">Bienvenue sur Lila</h1>
</div>
<div class="row">
    <div class="col s12 z-depth-1">
        <h4>Recherche par arrêt : </h4>
        <form action="{% url 'search.stop' %}" method="post" class="col s12 form" id="search-form">
            {% csrf_token %}
            <div class="row">
                <div class="input-field col s12">
                    {{ form.stop }}
                    <label for="id_stop">Arrêt</label>
                </div>
                {{ form.long_name }}
            </div>

            <div class="suggestions collection"></div>
            <div class="row center">
                <button class="btn waves-effect waves-light" type="submit" name="action">Valider
                    <i class="mdi-content-send right"></i>
                </button>
            </div>
        </form>
    </div>
</div>

{% if stop_routes %}
<ul class="collection">
    {% for sr in stop_routes %}
    <li class="collection-item avatar">
        <div class="circle" style="background-color: {{ sr.route.color }}">{{ sr.route.short_name }}</div>
        <span class="title">
            <a href="{% url 'horaires.view' sr.id %}">{{ sr.route.long_name}}</a>
        </span>
        <p class="subtitle">      
        <i class="tiny mdi-navigation-arrow-forward sens"></i>
        {{ sr.terminus }}
        </p>
    </li>
    {% endfor %}
</ul>
{% endif %}

{% endblock %}